system/base/baselayout/files/pisilinux-release
=> Revert "baselayout"

system/base/nettle/pspec.xml, system/devel/libarchive/pspec.xml
=> nettle-3.1.1 and libarchive with nettle in repo.

system/base/rsyslog/actions.py, system/base/rsyslog/pspec.xml
=> rsyslog verbump, add needed directory

kernel/drivers/ndiswrapper/actions.py, kernel/drivers/ndiswrapper/files/ndiswrapper-1.59.patch, kernel/drivers/ndiswrapper/pspec.xml, kernel/drivers/ndiswrapper/translations.xml
=> ndiswrapper in main

system/devel/libxslt/pspec.xml
08e94e01defc ~ # /git/build/checkelf -s -x libxslt-devel
Package: libxslt-devel
----------------------
Written dependencies           Detected dependencies          Missing dependencies
----------------------------------------------------------------------------------
libxslt                        libxml2-devel (devel)          libxml2-devel
=> libxslt: libxslt-devel: dep add

system/base/dbus/pspec.xml, system/base/util-linux/pspec.xml
=> dbus and util-linux 

system/devel/libtool/pspec.xml
emul3bit build need glibc-32bit.
=> fix build emul32 bit

system/base/perl/actions.py, system/base/perl/files/perl-5.10.0-x86_64-io-test-failure.patch, system/base/perl/files/perl-5.14.1-offtest.patch, system/base/perl/pspec.xml
=> perl update ,

system/base/glib2/pspec.xml, system/devel/gobject-introspection/pspec.xml
This reverts commit 16c12c8f6942aa003f89ad3ee6f12bd3c1c60322.
=> Revert " update glib2 and gobject-introspection"

system/base/eudev/pspec.xml
fix checkelf, 
libutil-linux dep.
remove unneeded conflict and replace tag.
=> eudev-3.2 update

system/base/piksemel/pspec.xml
=> rebuild with new toolchain

system/base/dbus/actions.py, system/base/dbus/pspec.xml
=> dbus update,

system/base/baselayout/files/os-release, system/base/baselayout/pspec.xml
=> os-release update

system/base/kmod/actions.py, system/base/kmod/pspec.xml
=> fix symlinks

programming/language/python3/python3-packaging/actions.py, programming/language/python3/python3-packaging/pspec.xml, programming/language/python3/python3-packaging/translations.xml, programming/language/python3/python3-setuptools/pspec.xml, system/devel/gmp/actions.py, system/devel/gmp/pspec.xml, system/devel/gmp/translations.xml
=> version bumps

programming/language/python3/python3-setuptools/pspec.xml
This reverts commit 5281c90c3d738c94a1fe062940bde0b4f9854977.
=> Revert "python3-setuptools 54.0.0"

system/base/pisi/actions.py, system/base/pisi/files/pot_file_and_ru_translation.patch, system/base/pisi/pspec.xml
Also else, the pull request is at [github.com/pisilinuxnew/pisi](https://github.com/PisiLinuxNew/pisi).
=> pisi rebuild with translation patch.

system/devel/gc/pspec.xml
Also, fix license (it is MIT, not BSD or GPL).
=> Update gc to 8.2.2

system/boot/grub2/pspec.xml
=> grub2 themes update

system/boot/grub2/files/grub-defaults
Also enable savedefault for a saner configuration.
=> Fix boolean declarations
